services:
    web:
        image: nginx:latest
        container_name: web
        build:
            context: ./web
            dockerfile: Dockerfile
        ports:
            - 80:80
            - 443:443
        networks:
            - app-network
        depends_on:
            - api
    api:
        container_name: api
        build: api
        ports:
          - 8080:8080
        networks:
            - app-network
        depends_on:
            - mongo
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    mongo:
        image: mongo:latest
        container_name: mongo
        restart: always
        ports:
            - 27017:27017
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
